# This workflow will upload a Python Package to PyPI when a release is created
# For more information see: https://docs.pypi.org/trusted-publishers/using-a-publisher/

name: Upload Python Package

on:
  release:
    types: [created]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Set release tag in VERSION
        run: echo "${{ github.event.release.tag_name }}" > VERSION

      - name: Install dependencies
        run: pip install -U pip setuptools wheel twine

#      - name: Run tests
#        run: |
#          pip install -r requirements.txt || pip install -r requirements-dev.txt || true
#          pytest || echo "No tests found"

      - name: Build package
        run: python setup.py sdist bdist_wheel

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI }}

      - name: List files in dist
        run: ls -haltR dist

      - name: Persist wheels directory
        uses: actions/upload-artifact@v4
        with:
          name: wheel_${{ github.event.release.tag_name }}
          path: dist/*.whl
          if-no-files-found: error
